docs/AboutUs.md
docs/team/m0destly.md

Edit AboutUs.md with Yun Hong's information

---

docs/AboutUs.md
docs/team/deannapoh.md

Edit AboutUs.md with Deanna's information

---

README.md

Acknowledge original source of the code

---

docs/DeveloperGuide.md

Update DeveloperGuide.md NFRs

---

docs/DeveloperGuide.md

Update DeveloperGuide.md to include user target user and user stories

---

docs/AboutUs.md
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Role.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Add 'role' parameter

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/TagCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/TagCommandParser.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

Add tag command

---

src/main/java/seedu/address/ui/MainWindow.java

Modify save feature

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java

Add Delete command

---

src/main/java/seedu/address/model/person/Phone.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PhoneTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Resolve minor bugs in add command

---

build.gradle

Update binary file name to HireHive.jar

---

src/main/java/hirehive/address/model/util/SampleDataUtil.java
src/test/java/hirehive/address/model/util/SampleDataUtilTest.java

Update sample data

---

src/main/java/hirehive/address/model/person/Name.java
src/main/java/hirehive/address/model/person/Person.java
src/test/java/hirehive/address/model/person/PersonTest.java

Change person name comparisons to become case-insensitive

---

src/main/java/hirehive/address/logic/commands/AddCommand.java
src/main/java/hirehive/address/logic/parser/AddCommandParser.java
src/main/java/hirehive/address/model/person/Person.java
src/main/java/hirehive/address/model/tag/Tag.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/hirehive/address/logic/LogicManagerTest.java
src/test/java/hirehive/address/logic/commands/CommandTestUtil.java
src/test/java/hirehive/address/logic/parser/AddCommandParserTest.java
src/test/java/hirehive/address/logic/parser/AddressBookParserTest.java
src/test/java/hirehive/address/model/person/PhoneTest.java
src/test/java/hirehive/address/testutil/DefaultPersonBuilder.java
src/test/java/hirehive/address/testutil/DefaultPersonUtil.java
src/test/java/hirehive/address/testutil/PersonBuilder.java
src/test/java/hirehive/address/testutil/TypicalPersons.java

Initialise default tags to 'Applicant'

---

src/main/java/hirehive/address/logic/commands/DeleteCommand.java
src/main/java/hirehive/address/logic/commands/queries/NameQuery.java
src/main/java/hirehive/address/logic/parser/DeleteCommandParser.java
src/main/java/hirehive/address/model/person/NameContainsKeywordsPredicate.java
src/test/java/hirehive/address/logic/LogicManagerTest.java
src/test/java/hirehive/address/logic/commands/DeleteCommandTest.java
src/test/java/hirehive/address/logic/parser/AddressBookParserTest.java
src/test/java/hirehive/address/logic/parser/DeleteCommandParserTest.java

Update delete command to new format

---

src/main/java/hirehive/address/logic/Messages.java
src/main/java/hirehive/address/logic/commands/FilterCommand.java
src/main/java/hirehive/address/logic/parser/AddressBookParser.java
src/main/java/hirehive/address/logic/parser/FilterCommandParser.java
src/main/java/hirehive/address/model/person/PersonContainsTagPredicate.java
src/main/java/hirehive/address/model/tag/Tag.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/hirehive/address/logic/commands/FilterCommandTest.java
src/test/java/hirehive/address/logic/parser/AddressBookParserTest.java
src/test/java/hirehive/address/logic/parser/FilterCommandParserTest.java
src/test/java/hirehive/address/model/person/PersonContainsTagPredicateTest.java
src/test/java/hirehive/address/testutil/TypicalPersons.java

Add filter command for tags

---

docs/UserGuide.md

Update save description for UG

---

src/main/java/hirehive/address/logic/commands/DeleteCommand.java
src/main/java/hirehive/address/logic/parser/ParserUtil.java
src/main/java/hirehive/address/model/tag/Tag.java
src/main/java/hirehive/address/model/util/SampleDataUtil.java
src/main/java/hirehive/address/storage/JsonAdaptedTag.java
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/java/hirehive/address/logic/commands/CommandTestUtil.java
src/test/java/hirehive/address/logic/commands/EditCommandTest.java
src/test/java/hirehive/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/hirehive/address/logic/commands/FilterCommandTest.java
src/test/java/hirehive/address/logic/parser/AddCommandParserTest.java
src/test/java/hirehive/address/logic/parser/AddressBookParserTest.java
src/test/java/hirehive/address/logic/parser/EditCommandParserTest.java
src/test/java/hirehive/address/logic/parser/FilterCommandParserTest.java
src/test/java/hirehive/address/logic/parser/ParserUtilTest.java
src/test/java/hirehive/address/model/AddressBookTest.java
src/test/java/hirehive/address/model/person/PersonContainsTagPredicateTest.java
src/test/java/hirehive/address/model/person/PersonTest.java
src/test/java/hirehive/address/model/person/UniquePersonListTest.java
src/test/java/hirehive/address/model/tag/TagTest.java
src/test/java/hirehive/address/testutil/EditPersonDescriptorBuilder.java

Update tag to only have specific values

---

src/main/java/hirehive/address/logic/commands/CommandResult.java
src/main/java/hirehive/address/logic/commands/ListCommand.java
src/main/java/hirehive/address/ui/MainWindow.java
src/test/java/hirehive/address/logic/commands/CommandResultTest.java

Update save to show only when successful edits made

---

src/main/java/hirehive/address/logic/commands/NoteCommand.java
src/main/java/hirehive/address/ui/MainWindow.java

Fix MainWindow and Note command bugs

---

docs/AboutUs.md
docs/UserGuide.md
src/main/resources/view/MainWindow.fxml

Add glossary to UG and update MainWindow display

---

src/main/java/hirehive/address/logic/commands/DateCommand.java
src/main/java/hirehive/address/logic/commands/EditCommand.java
src/main/java/hirehive/address/logic/commands/SortCommand.java
src/main/java/hirehive/address/logic/parser/AddCommandParser.java
src/main/java/hirehive/address/logic/parser/AddressBookParser.java
src/main/java/hirehive/address/logic/parser/DeleteCommandParser.java
src/main/java/hirehive/address/logic/parser/FindCommandParser.java
src/main/java/hirehive/address/logic/parser/NoteCommandParser.java
src/main/java/hirehive/address/logic/parser/ParserUtil.java
src/main/java/hirehive/address/logic/parser/TagCommandParser.java
src/main/java/hirehive/address/model/Model.java
src/main/java/hirehive/address/model/ModelManager.java
src/main/java/hirehive/address/model/person/InterviewDate.java
src/test/java/hirehive/address/logic/commands/AddCommandTest.java
src/test/java/hirehive/address/logic/commands/NoteCommandTest.java
src/test/java/hirehive/address/logic/commands/SortCommandTest.java
src/test/java/hirehive/address/model/ModelManagerTest.java

Add Sort command

---

docs/UserGuide.md

Update user guide details

---

src/main/java/hirehive/address/logic/Messages.java
src/main/java/hirehive/address/logic/commands/AddCommand.java
src/main/java/hirehive/address/logic/commands/EditCommand.java
src/main/java/hirehive/address/model/person/Name.java

Fix [Add] bugs

---

src/main/java/hirehive/address/logic/commands/AddCommand.java
src/main/java/hirehive/address/logic/commands/NewNoteCommand.java
src/main/java/hirehive/address/logic/commands/NoteCommand.java
src/main/java/hirehive/address/logic/parser/AddCommandParser.java
src/main/java/hirehive/address/logic/parser/AddressBookParser.java
src/main/java/hirehive/address/logic/parser/NewNoteCommandParser.java
src/main/java/hirehive/address/model/person/Note.java
src/main/java/hirehive/address/model/person/Person.java
src/main/java/hirehive/address/ui/NoteWindow.java
src/test/java/hirehive/address/logic/LogicManagerTest.java
src/test/java/hirehive/address/logic/commands/NewNoteCommandTest.java
src/test/java/hirehive/address/logic/commands/NoteCommandTest.java
src/test/java/hirehive/address/logic/parser/AddCommandParserTest.java
src/test/java/hirehive/address/logic/parser/AddressBookParserTest.java
src/test/java/hirehive/address/logic/parser/NewNoteCommandParserTest.java
src/test/java/hirehive/address/logic/parser/NoteCommandParserTest.java
src/test/java/hirehive/address/model/person/NoteTest.java

Make newnote command to add notes separately

---

docs/UserGuide.md

Edit User Guide: Introduction, Help, Add, List, Clear, Exit, FAQ, Known issues

---

src/main/java/hirehive/address/ui/NoteWindow.java
src/main/resources/view/NoteWindow.css
src/main/resources/view/NoteWindow.fxml

Update NoteWindow UI, include copy button

---

src/main/java/hirehive/address/logic/parser/DeleteCommandParser.java

Update parser logic to prevent multiple inputs for Delete

---

src/main/java/hirehive/address/logic/commands/FilterCommand.java
src/main/java/hirehive/address/logic/parser/FilterCommandParser.java

Fixes #109 
Fixes #110 
Fixes #115

Fix bugs in FilterCommand.java

---

src/main/java/hirehive/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

Add InterviewDate label

---

src/main/java/hirehive/address/logic/Messages.java
src/main/java/hirehive/address/logic/commands/TagCommand.java
src/main/java/hirehive/address/logic/parser/TagCommandParser.java

Allow tag command to edit tag by index 

---

src/main/java/hirehive/address/logic/Messages.java
src/main/java/hirehive/address/logic/commands/AddCommand.java
src/main/java/hirehive/address/logic/commands/ClearCommand.java
src/main/java/hirehive/address/logic/commands/CommandResult.java
src/main/java/hirehive/address/logic/commands/DeleteCommand.java
src/main/java/hirehive/address/logic/commands/EditCommand.java
src/main/java/hirehive/address/logic/commands/ExitCommand.java
src/main/java/hirehive/address/logic/commands/HelpCommand.java
src/main/java/hirehive/address/logic/commands/NewNoteCommand.java
src/main/java/hirehive/address/logic/commands/NoteCommand.java
src/main/java/hirehive/address/logic/commands/TagCommand.java
src/main/java/hirehive/address/ui/MainWindow.java
src/test/java/hirehive/address/logic/commands/AddCommandIntegrationTest.java
src/test/java/hirehive/address/logic/commands/ClearCommandTest.java
src/test/java/hirehive/address/logic/commands/CommandResultTest.java
src/test/java/hirehive/address/logic/commands/DeleteCommandTest.java
src/test/java/hirehive/address/logic/commands/EditCommandTest.java
src/test/java/hirehive/address/logic/commands/ExitCommandTest.java
src/test/java/hirehive/address/logic/commands/HelpCommandTest.java
src/test/java/hirehive/address/logic/commands/NewNoteCommandTest.java
src/test/java/hirehive/address/logic/commands/NoteCommandTest.java

Fixes #166 
*Not included for DateCommand yet

Update save message to show for relevant commands only

---

src/main/java/hirehive/address/logic/Messages.java
src/main/java/hirehive/address/logic/commands/DisplayNoteCommand.java
src/main/java/hirehive/address/logic/commands/NewNoteCommand.java
src/main/java/hirehive/address/logic/parser/DisplayNoteCommandParser.java
src/main/java/hirehive/address/logic/parser/NewNoteCommandParser.java
src/test/java/hirehive/address/logic/commands/DisplayNoteCommandTest.java
src/test/java/hirehive/address/logic/commands/NewNoteCommandTest.java
src/test/java/hirehive/address/logic/parser/AddressBookParserTest.java
src/test/java/hirehive/address/logic/parser/DisplayNoteCommandParserTest.java
src/test/java/hirehive/address/logic/parser/NewNoteCommandParserTest.java

Fix note bugs for same names

---

src/main/java/hirehive/address/logic/commands/ScheduleCommand.java
src/test/java/hirehive/address/logic/commands/ScheduleCommandTest.java

Update schedule command to show save message

---

src/main/java/hirehive/address/commons/util/StringUtil.java
src/main/java/hirehive/address/logic/parser/EditCommandParser.java
src/main/java/hirehive/address/logic/parser/ParserUtil.java
src/main/java/hirehive/address/logic/parser/ReminderCommandParser.java
src/test/java/hirehive/address/commons/util/StringUtilTest.java
src/test/java/hirehive/address/logic/parser/EditCommandParserTest.java
src/test/java/hirehive/address/logic/parser/ParserUtilTest.java
src/test/java/hirehive/address/logic/parser/ReminderCommandParserTest.java

Fix integer overflow issues

---

docs/DeveloperGuide.md

DG: Add acknowledgements; Edit hyperlinks; Add use case for add, list, edit and find command 

---

docs/UserGuide.md

fixes #277 
fixes #264 
fixes #258 
fixes #254 
fixes #246 
fixes #242 
fixes #238 
fixes #230 
fixes #229 
fixes #219 
fixes #218

Fix Add Command part of UG 

---

src/main/java/hirehive/address/logic/parser/CliSyntax.java
src/test/java/hirehive/address/logic/parser/ScheduleCommandParserTest.java

Change date prefix to "id/"

---

src/main/java/hirehive/address/logic/Messages.java

Update save message

---

src/main/java/hirehive/address/logic/Messages.java
src/main/java/hirehive/address/logic/commands/DisplayNoteCommand.java
src/main/java/hirehive/address/logic/parser/DisplayNoteCommandParser.java
src/main/java/hirehive/address/ui/NoteWindow.java
src/main/java/hirehive/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

Add note indicator in personCard and fix copy bug

---

src/main/java/hirehive/address/logic/Messages.java

Edit message on what user should do when there are duplicate names so it is clearer

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/hirehive/address/model/person/Person.java
src/main/java/hirehive/address/model/person/Role.java
src/test/java/hirehive/address/model/person/PersonTest.java

Revert add command

---

docs/UserGuide.md

Update delete, edit, find command in UG

---

src/main/java/hirehive/address/logic/Messages.java
src/main/java/hirehive/address/logic/commands/DeleteCommand.java
src/main/java/hirehive/address/logic/commands/EditCommand.java
src/main/java/hirehive/address/logic/commands/ListCommand.java
src/main/java/hirehive/address/logic/commands/ScheduleCommand.java
src/main/java/hirehive/address/logic/commands/queries/NameQuery.java
src/main/java/hirehive/address/model/Model.java
src/main/java/hirehive/address/model/ModelManager.java
src/test/java/hirehive/address/logic/commands/AddCommandTest.java

Allow consecutive filter commands to stack

---

docs/DeveloperGuide.md

Add use case for sort command

---

docs/UserGuide.md

Update UG save issue
